name: Run All Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Groovy
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install groovy
        source "$HOME/.sdkman/bin/sdkman-init.sh" && groovy -version  # Verify installation

    - name: Compile Groovy Classes
      run: |
        # Compile the Groovy classes
        groovyc -d ./bin ./src/com/genexus/*.groovy
        
    - name: Run All Tests
      run: |
        # Ensure the test directory is set up correctly
        echo "Running all Groovy tests..."
        source "$HOME/.sdkman/bin/sdkman-init.sh"  # Ensure SDKMAN! is sourced
        # Run all Groovy test files in the 'test' directory
        find ./test -name '*.groovy' | while read testFile; do
            echo "Running $testFile..."
            groovy -cp ./bin "$testFile"
        done
        echo "All tests executed!"
