name: Run All Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'

   - name: Install Groovy
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install groovy

    - name: Run All Tests
      run: |
        # Ensure the test directory is set up correctly
        echo "Running all Groovy tests..."
        
        # Run all Groovy test files in the tests directory
        for testFile in ./test/*.groovy; do
            echo "Running $testFile..."
            groovy "$testFile"
        done

        echo "All tests executed!"
